from pathlib import Path
import json,csv,sqlite3,re,collections,datetime
ROOT=Path(__file__).resolve().parent/'OpenMath-Judging';OUT=ROOT/'review';d=json.loads((OUT/'review-data.json').read_text(encoding='utf8'))
rs={r['id']:r for r in d['results']};ts={t['id']:t for t in d['teams']}
notes={
 'KOBON':{'frontier':'Lower constructions: independently recounted HTPeo K(39)>=471, Rohith K(39)>=470 and66 catalogue witnesses. Raj claims arbitrary-multiplicity K(18)<=94, restricted <=93, K(14)=54 and triple-point even-order bounds; the formal geometry transfer is incomplete. Jamie conditional exclusions do not establish an unconditional bound.','interaction':'At each SAME n, compare a straight-line lower witness to an upper bound with matching degeneracy assumptions. n39 lower and n18 upper do not numerically close one another. Normalize wiring words, line coordinates, multiplicities and bounded faces; pseudoline lower witnesses require realizability.','paper':'An exact-construction catalogue with independent recounts is plausible now. A joint construction/upper-bound paper is conditional on Raj closing the geometric soundness chain. Attribute pre-existing93/18 witnesses and imported gallery configurations; give authors credit by actual work, not leaderboard presence.','collective':'Conservative virtual entrant: one current parent-family P1=.01 (3.5739 points with focus bonus); no sum of the66 arrangements. Potential P2=.05 /17.8695 only after the upper-bound proof chain is accepted.'},
 'COLLATZ':{'frontier':'E05 and E08 cover exactly the same1765 odd residue classes modulo4096; E10 covers1504 classes, all within that union. E66 lacks a complete inspectable packet. This is partial certified descent, not all-integer Collatz.','interaction':'Compare the depth/descent inequalities and canonical rule basis, not counts of rules or private weighted oracle scores. Compression and bounded-classification lemmas may differ while convergence coverage is identical.','paper':'One shared exact checker/coverage paper is more credible than three papers claiming the same region. Include independent provenance and genuinely different bounded-classification or compression methods.','collective':'Virtual family credit stays p=.01, 6.555824 with thefocus bonus; duplicate/subset coverage adds zero. Individual sealed-provenance credit is a separate eligibility decision.'},
 'RAMSEY-K4':{'frontier':'HTPeo exact bound ~.030139912 is stronger than Sakana ~.0301409323 and the located McKay reference .0301422734319. E01 and several account leads lack graphs/weights. No lower bound matching the upper is supplied.','interaction':'Reuse a faithful generic weighted-template lifting theorem to validate every exact graph packet under one density convention. Rank exact rationals after validation; board values alone cannot establish an infinite theorem.','paper':'A strongest verified weighted construction with a generic formal lifting library is promising. Verify the frozen reference, stronger prior literature and sealed independence before attributing novelty.','collective':'One conservative P2=.05 frontier, 35.28 under proposed D840 and conservative b=1. If inclusion in the frozen focus set is confirmed, b=1.1 gives38.808.'},
 'MATRIX-3':{'frontier':'Chandra claims a138-nonzero rank23 rational tensor decomposition and structural family. Only complete u-vectors and truncated v/w captures are available. Sakana proves restricted one-leg uniqueness for known139 seeds, not global minimal support.','interaction':'Once all U,V,W arrive, check the entire tensor identity coefficient by coefficient, compare support/gauge conventions, then instantiate one-leg rigidity on the138 seed. Rigidity and an improved construction complement each other but cannot prove a global optimum.','paper':'A138 construction plus rational support/gauge structure and comparative rigidity could be a joint paper after originals validate. Missing vectors are an explicit publication blocker.','collective':'Chandra current source hold0; conditional P2=.05 at D724 gives28.82968; Sakana restricted obstruction P1=.01 gives5.765936. One conservative frontier, not their sum; current mathematical acceptance is pending.'},
 'ERDOS3':{'frontier':'Leon/Cameron and Wilson supply overlapping extremal/dyadic equivalences; Jamie a conclusion bridge. Three-term Kelley–Meka and Gowers4 material is known mathematics. Neither side of the all-length equivalence is discharged. Sakana proves a mod13 diagonal-pullback obstruction; its4-AP sum>4.44 belongs to Erdős169, not a solution here.','interaction':'Normalize progression length, density/maxCard and dyadic summability definitions. Align exact endpoints and imported dependencies; preserve conditional analytic hypotheses.','paper':'A reusable formal interface joining extremal counting and reciprocal-sum conclusions is plausible. Keep the all-length density estimate clearly open; deduplicate the equivalence while recording independent implementations.','collective':'No full solution. Sakana narrow method-obstruction proposal p=.01 gives4.997036; known equivalences earn no original-result points. Proposed M2 frontier families: dyadic equivalence, AP/conclusion interface, three-term integration, Gowers4 estimate. Separate implementation novelty from mathematical novelty.'},
 'ERDOS169':{'frontier':'Sakana finite4-AP-free positive set has harmonic sum>4.44; Leon/Cameron report4.314 in a fixed-N benchmark. The located prior numerical claim4.4397534742 is smaller than4.44.','interaction':'Compare exact same-domain reciprocal sums; N-dependent benchmarks require matching size/domain. Unbounded harmonic sums do not follow from these finite examples.','paper':'A formal finite construction and reusable AP-free certificate method may merit a short paper. Preserve lower-scoring fixed-N work only with a distinct algorithmic/formal contribution.','collective':'One original-family P2=.05 frontier at D538:14.4722, not two independent summed scientific bounds.'},
 'DMS':{'frontier':'HTPeo gives125-source special-family five-colour work and98-module reductions, finite six-colour classification up to14 vertices and endpoints retaining OPEN hypotheses. Not every subcubic graph is covered.','interaction':'Petersen/perfect-matching infrastructure supports concrete reductions. Container formalization is a prospective combinatorics resource, with no demonstrated DMS consequence this event.','paper':'A formal special-family/reduction library is plausible if claimed novelty survives known-class comparison. Separate original endpoints, known theorem formalization and still-open general lifting.','collective':'Conservative proposed P3=.15 at D574:49.4214; fallback P2=.05 gives16.4738 if only the narrower new scope is admitted.'},
 'BB6':{'frontier':'Available finite six-state halting traces tie or trail known records; board ties can come from different machines. Sakana reports1,235,211 steps/1519 ones, not the busy-beaver maximum. Tissue/adaptive models are different targets.','interaction':'Normalize machine tables, blank tape, head position, step counting, halting/ones/span conventions. Share bounded trace checking; do not merge machines from equal scores.','paper':'A generic formal bounded-machine certificate library could be useful; a numerical subrecord needs a separate method novelty claim.','collective':'Original-family proposal0. Preserve partial traces and possible reusable M2 targets, without inventing theorem credit.'},
 'GROTHENDIECK':{'frontier':'CHSH and tiny finite sign enumerations are known/baseline results. Sakana proves a three-row square-root1.5 bound and a four-point square-root2 enumeration; the universal constant remains untouched.','interaction':'Classify restricted dimensions/sign domains and compare exact finite certificates. A restricted proof is not a universal Grothendieck improvement.','paper':'Only a distinctly new reusable restricted formal theorem might justify a library note; current packets do not support a new universal-constant paper.','collective':'Original-family0; known restricted formalization credit must clear baseline overlap before M2 admission.'},
 'CERNY':{'frontier':'Qichao reports nine abstract core sections and a research paper. The original27MB source packet is absent; generic potential/layered and inverse-shrink interfaces do not prove the all-n reset bound.','interaction':'Deduplicate to five coherent M2 groups; prove a literal transition-system bridge and all-parameter hypotheses before claiming Černý progress.','paper':'A scoped method-obstruction/interface paper is possible only after the actual source is retrieved and checked; no general conjecture-resolution paper.','collective':'Original-family0. Five M2 groups are potential proposals on hold, not verified delivered formalizations.'},
 'HEILBRONN9':{'frontier':'Nine points in the reference triangle T; attempted target .027426211734693878. Coverage has2581 unresolved and529 missing leaves, plus incomplete boundary coverage. Local solver PROVED labels are not a global proof.','interaction':'Unify canonical box IDs and split trees, handle corners/boundary, use outward-rounded certified bounds and prove cover completeness. Preserve successful local subcases.','paper':'Currently a reproducible computational partial-coverage report, not a universal nine-point theorem. Publication of a global bound requires every leaf closed or covered.','collective':'Current original-family0; percentages of solved boxes do not determine p.'},
 'UNITARY':{'frontier':'Matt proposes asymptotic21/48*4^n versus the located published22/48 baseline. The n3 circuit experiments do not prove exact surjectivity for every unitary, and the inductive manuscript is nonrigorous.','interaction':'Bridge exact circuit construction, worst-case completeness and uniform induction; numerical synthesis examples are useful experiments only.','paper':'A methods/experimental note is possible; a new worst-case bound awaits an actual proof and formalized universal construction.','collective':'Current formal-only0; no score from the claimed coefficient alone.'}
}
if (OUT/'chandra-independent-tensor-check.json').exists():
 notes['MATRIX-3']={'frontier':'Chandra complete pinned original is now available. Our checker confirms all729 rational tensor identities for support138, its gauged138 version and core1809support143, plus exact scaled Lean-data correspondence. The rational one-parameter138family is independently checked outside s=0,-2. Sakana one-leg rigidity for known139seeds is narrower.','interaction':'Use the verified138tensor as a new seed for restricted one-leg rigidity and compare the same support/gauge conventions. The literal138support pattern fails4GF(2) identities; sign-only search cannot produce this pattern. Fixed-factor rigidity still cannot prove global137impossibility.','paper':'Strong candidate: exact138construction plus rational family and restricted rigidity. Constant arithmetic/runtime claims, global inequivalence, dimension and boundary minimality need separate proofs. Attribute source-specific work and repair stale README scale-factor entries.','collective':'Conservative one-family P2=.05 at D724 gives28.82968, pending fresh closure and priority/intake. Sakana P1=.01 gives5.765936 individually; their scientific frontier does not sum these overlapping family points.'}
for k,p in d['problems'].items():
 supporting=[r['id'] for r in d['results'] if (k=='ERDOS3' and str(r['family_id']).startswith(('M2-E3-','M2-AP-CONCLUSION','M2-GOWERS4'))) or (k=='CERNY' and str(r['family_id']).startswith('CERNY-PART-')) or (k=='DMS' and r['id']=='E08-G-PM')]
 p['supporting_result_ids']=supporting;p['contributors']=list(dict.fromkeys(p['contributors']+[rs[x]['team_id'] for x in supporting]))
 n=notes.get(k)
 if not n:
  related=[rs[x] for x in p['result_ids']];n={'frontier':' '.join(r['title']+': '+r['exact_claim'][:220] for r in related[:3]),'interaction':'Supporting lemmas and corollaries belong to the same scope union. '+('This known mathematics may support reusable libraries; there is no original-result synergy bonus.' if p['status_gate']=='known_formalization_target' else 'Any transfer to a parent or another problem requires a proved scope-preserving bridge.'),'paper':'Candidate building block only; preserve source hypotheses, exact priority comparison, proof closure and contribution-based authorship.','collective':'Virtual family representative '+str(p['collective_frontier_representative'])+'; conservative one-family points '+p['collective_frontier_points_once']+'. M2 is separate when applicable.'}
 p['scientific_profile']=n
 p['virtual_entrant']={'id':'P-'+k,'score_once':p['collective_frontier_points_once'],'overlap_policy':'Maximum conservative admitted-scope proposal; complementary results retained descriptively. No automatic increase of p, no extra award and no claim that a combined proof was already built.'}
 text=p['id']+'\nCanonical target: '+p['statement']+'\nD proposal='+str(p['D_0_1000_proposed'])+'/1000; intrinsic='+str(p['intrinsic_0_10'])+'/10\n'+p['D_origin']+'\n\n'+'\n\n'.join(a.upper()+': '+b for a,b in n.items())+'\n\nCONTRIBUTION MAP\n'
 for rid in p['result_ids']+supporting:
  r=rs[rid];text+='\n'+rid+' / '+ts[r['team_id']]['name']+'\n'+r['exact_claim']+'\n'+r['thoughts']+'\nNovelty: '+r['novelty']+'\nFormalization: '+r['formalization_and_correctness']+'\nProposed '+r['proposed_modality']+'; p='+str(r['proposed_p'])+'; points='+str(r['proposed_points'])+'; full review: entries/'+rid+'.txt\n'
 text+='\nOPDP INPUTS AND RATIONALE\n'+json.dumps({a:p[a] for a in ['inputs','calculation','intrinsic_factors','axis_rationales','parent_links','sources']},ensure_ascii=False,indent=2)
 (OUT/'problems'/(k+'.txt')).write_text(text,encoding='utf8')
def short(s,n):
 s=re.sub(r'\s+',' ',s).strip()
 return s if len(s)<=n else s[:n].rsplit(' ',1)[0]+'…'
for t in d['teams']:
 text=t['id']+' '+t['name']+'\nAUTHORS: '+(', '.join(t['authors']) or 'Unresolved account attribution')+'\nPROPOSED S='+t['adjusted_S']+' / A='+t['adjusted_A']+' / M2 families='+str(t['M2_proposed_integer_count'])+' (adjusted ranking value '+t['M2_adjusted_overall_value']+')\n'+t['thoughts']+'\nReview budget: '+str(t['review_minutes'])+' minutes. Numerical proposals are contingent on acceptance and the listed checks.\n\n'
 primary=[rs[x] for x in t['result_ids'] if rs[x]['proposed_modality'] not in ['M2','NONE']]
 for r in primary:
  if t['id']=='E57' and r['id']!='E57-PORTFOLIO':
   text+=r['id']+' | '+short(r['exact_claim'],165)+' | '+str(r['proposed_points'])+' points before family dedup; see entries/'+r['id']+'.txt\n';continue
  text+=r['id']+' | '+r['title']+'\n'+short(r['exact_claim'],330)+'\nAssessment: '+short(r['thoughts'],550)+'\nNovelty: '+short(r['novelty'],260)+'\nFormal: '+short(r['formalization_and_correctness'],310)+'\nProposal: '+r['proposed_modality']+'; D='+str(r['D_proposed'])+'; p='+str(r['proposed_p'])+'; family points='+str(r['proposed_points'])+'. Full evidence/checks: entries/'+r['id']+'.txt\n\n'
 m2=[rs[x] for x in t['result_ids'] if rs[x]['proposed_modality']=='M2']
 if m2:
  text+='KNOWN-THEOREM FORMALIZATIONS\n'+t['M2_rationale']+'\nKnown mathematical results; potential credit is new faithful reusable formalization, with baseline overlap and pinned closure checked separately.\n'
  for r in m2:text+=r['id']+' | '+r['title']+' | '+short(r['exact_claim'],210)+' | entries/'+r['id']+'.txt\n'
 if not primary and not m2:text+='Disposition: '+t['status']+'\nCurrent proposed credit0: no inspectable eligible result packet. This is a payload/disposition hold, not a mathematical rejection.\n'
 text+='\nPRIORITY SIGN-OFF\n'+ '\n'.join(dict.fromkeys(g for x in t['result_ids'] for g in rs[x]['acceptance_gaps']))+'\n\nRepo: '+str(t['repo'])+'\nPinned commit: '+str(t['commit'])+'\nIndividual authors share the packet; no unsupported per-author point split. File summaries are visible under Classified files.\n'
 (OUT/'people'/(t['id']+'.txt')).write_text(text,encoding='utf8')
for person in d['people']:
 (OUT/'people'/(person['person_id']+'.txt')).write_text('PERSON: '+person['display_name']+'\n'+person['individual_contribution_map']+'\n\n'+(OUT/'people'/(person['entrant_id']+'.txt')).read_text(encoding='utf8'),encoding='utf8')
d['scientific_profile_notes']=notes;d['file_summary_coverage']=json.loads((OUT/'file-summary-coverage.json').read_text(encoding='utf8'))
if (OUT/'chandra-independent-tensor-check.json').exists():d['new_independent_checks']=['chandra-independent-tensor-check.json','chandra-independent-family-check.json','chandra-original-source-index.json']
d['review_budget']['total_minutes']=sum(d['review_budget'][k] for k in ['entry_minutes','problem_frontier_minutes','decision_and_reconciliation_minutes','breaks_and_margin_minutes'])
(OUT/'review-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
with (OUT/'score-signoff.csv').open('w',newline='',encoding='utf-8-sig') as f:
 w=csv.writer(f);w.writerow(['entry','name','proposed_S','proposed_A','M2_family_count','adjusted_M2_ranking_value','approve_or_hold','chair_reason','formal_closure','novelty','eligibility','D_ratifed'])
 for t in d['teams']:w.writerow([t['id'],t['name'],t['adjusted_S'],t['adjusted_A'],t['M2_proposed_integer_count'],t['M2_adjusted_overall_value'],'PENDING','','PENDING','PENDING','PENDING','PENDING'])
with (OUT/'contribution-signoff.csv').open('w',newline='',encoding='utf-8-sig') as f:
 w=csv.writer(f);w.writerow(['result','entry','family','track','D','p','points_before_union','in_family_union','approval','reason'])
 for r in d['results']:w.writerow([r['id'],r['team_id'],r['family_id'],r['proposed_modality'],r['D_proposed'],r['proposed_p'],r['proposed_points'],r['selected_for_family_union'],'PENDING',''])
print(json.dumps({'profiles':len(d['people']),'minutes':d['review_budget']['total_minutes'],'file_summaries':d['file_summary_coverage']['summaries']}))

