name = "openmath"
defaultTargets = ["ReviewExisting", "ReviewAdditions"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.copyright.formalConjectures = false
weak.linter.style.namespace = true
weak.linter.style.stubs = true
weak.linter.style.openClassical = true

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "137aec5c7abd3aa61f7a73138a97279acfc79e93"

[[lean_lib]]
name = "Openmath"

[[lean_lib]]
name = "ReviewExisting"

[[lean_lib]]
name = "ReviewAdditions"

[[lean_lib]]
name = "VerifiedAdditions"
roots = ["AffinePaletteBarrier", "CherryBoundary", "ComponentClosure", "ComponentUnions", "CutResilience", "CycleComposition", "DeletedGadget", "GlobalSelectors", "HaarComponents", "HaarInfinite", "HamiltonianDeletion", "InfiniteAffinePaletteBarrier", "Main", "MatchingIdentification", "MatrixSampling", "MultigraphCut", "NormVariance", "Passage", "Piece", "PrescribedVertex", "PrimeChart", "Projection", "R1", "Regularity", "SkeletonB", "SkeletonK", "Substitution", "TwinDensityExtension", "UnitPorts"]

[[lean_lib]]
name = "SLT"
roots = ["SLT.RMT.MatBern"]

[[lean_lib]]
name = "IndependentTransversals"
roots = ["IndependentTransversals.GeneralHaxell"]
